/* GERADO AUTOMATICAMENTE por scripts/planilha_para_js.py — não edite à mão.
   Fonte: data/painel-processos-dados.xlsx */
window.PAINEL_DADOS = {
 "_gerado_em": "2026-07-23 15:38",
 "_fonte": "painel-processos-dados.xlsx",
 "Macroprocessos": [
  {
   "Codigo": "MP-01",
   "Nome": "Gestão Estratégica e Governança",
   "Categoria": "Gerencial",
   "Ordem": 1,
   "Descricao": "Formulação, desdobramento e monitoramento da estratégia corporativa, da governança e do desempenho institucional.",
   "Objetivo": "Garantir que a atuação da Companhia esteja alinhada à estratégia, com decisões baseadas em evidências.",
   "Unidade_Responsavel": "AE/GPE",
   "Dono_Processo": "Helena Castro — Gerente de Planejamento",
   "Entregas": "Plano Estratégico; Plano de Ação Anual; Relatórios de desempenho",
   "Clientes_Beneficiarios": "Diretoria Executiva; Conselho de Administração; Unidades internas",
   "Partes_Interessadas": "Ministério supervisor; Órgãos de controle; Sociedade",
   "Sistemas": "e-Codevasf; SEI; Painéis de BI",
   "Normativos_Aplicaveis": "Estatuto Social; Regimento Interno; Lei nº 13.303/2016",
   "Imagem_Bizagi": "img/diagramas/mp-01.svg",
   "Observacoes": null
  },
  {
   "Codigo": "MP-02",
   "Nome": "Gestão de Riscos, Integridade e Controles",
   "Categoria": "Gerencial",
   "Ordem": 2,
   "Descricao": "Identificação, avaliação e tratamento de riscos corporativos, integridade e controles internos (2ª linha).",
   "Objetivo": "Assegurar razoável segurança para o alcance dos objetivos institucionais.",
   "Unidade_Responsavel": "AE/GAG",
   "Dono_Processo": "Fernanda Alves — Gerente de Governança",
   "Entregas": "Política de Gestão de Riscos; Matriz de riscos corporativa; Plano de integridade",
   "Clientes_Beneficiarios": "Alta administração; Gestores de 1ª linha",
   "Partes_Interessadas": "Auditoria interna; CGU; TCU",
   "Sistemas": "SEI; Sistema de gestão de riscos",
   "Normativos_Aplicaveis": "Política de Gestão de Riscos (fictícia); IN Conjunta MP/CGU nº 01/2016",
   "Imagem_Bizagi": "img/diagramas/mp-02.svg",
   "Observacoes": null
  },
  {
   "Codigo": "MP-03",
   "Nome": "Desenvolvimento Territorial e Estruturação Produtiva",
   "Categoria": "Finalístico",
   "Ordem": 3,
   "Descricao": "Apoio a arranjos produtivos, inclusão socioeconômica e estruturação de cadeias produtivas nos vales.",
   "Objetivo": "Promover o desenvolvimento regional integrado e sustentável.",
   "Unidade_Responsavel": "AR/GDT",
   "Dono_Processo": "Eduardo Martins — Gerente de Desenvolvimento",
   "Entregas": "Projetos de estruturação produtiva; Convênios e instrumentos de repasse",
   "Clientes_Beneficiarios": "Produtores rurais; Cooperativas; Municípios",
   "Partes_Interessadas": "Parlamentares; Entes federados; Entidades parceiras",
   "Sistemas": "TransfereGov; SEI",
   "Normativos_Aplicaveis": "Lei nº 14.133/2021; Portarias de transferências voluntárias",
   "Imagem_Bizagi": "img/diagramas/mp-03.svg",
   "Observacoes": null
  },
  {
   "Codigo": "MP-04",
   "Nome": "Gestão de Empreendimentos de Irrigação",
   "Categoria": "Finalístico",
   "Ordem": 4,
   "Descricao": "Implantação, operação, manutenção e transferência de gestão de perímetros públicos de irrigação.",
   "Objetivo": "Ampliar a área irrigada produtiva com sustentabilidade hídrica e econômica.",
   "Unidade_Responsavel": "AI/GOM",
   "Dono_Processo": "Marcos Vinícius — Gerente de Operação",
   "Entregas": "Perímetros em operação; Água distribuída; Relatórios de O&M",
   "Clientes_Beneficiarios": "Irrigantes; Distritos de irrigação",
   "Partes_Interessadas": "ANA; Agências estaduais; Associações de usuários",
   "Sistemas": "SIG-Irrigação (fictício); SEI",
   "Normativos_Aplicaveis": "Lei nº 12.787/2013 (Política Nacional de Irrigação)",
   "Imagem_Bizagi": "img/diagramas/mp-04.svg",
   "Observacoes": null
  },
  {
   "Codigo": "MP-05",
   "Nome": "Revitalização de Bacias Hidrográficas",
   "Categoria": "Finalístico",
   "Ordem": 5,
   "Descricao": "Ações de recuperação hidroambiental, segurança hídrica e uso sustentável dos recursos naturais.",
   "Objetivo": "Contribuir para a revitalização das bacias dos rios São Francisco e Parnaíba.",
   "Unidade_Responsavel": "AR/GRB",
   "Dono_Processo": "Luciana Prado — Gerente de Revitalização",
   "Entregas": "Nascentes recuperadas; Obras hidroambientais; Sistemas de abastecimento",
   "Clientes_Beneficiarios": "Comunidades ribeirinhas; Municípios",
   "Partes_Interessadas": "Comitês de bacia; MMA; Órgãos ambientais",
   "Sistemas": "SEI; GeoPortal (fictício)",
   "Normativos_Aplicaveis": "Legislação ambiental aplicável",
   "Imagem_Bizagi": "img/diagramas/mp-05.svg",
   "Observacoes": null
  },
  {
   "Codigo": "MP-06",
   "Nome": "Gestão de Licitações e Contratos",
   "Categoria": "Suporte",
   "Ordem": 6,
   "Descricao": "Planejamento das contratações, seleção de fornecedores e gestão dos contratos administrativos da Companhia.",
   "Objetivo": "Prover contratações tempestivas, vantajosas e conformes à legislação.",
   "Unidade_Responsavel": "AA/GLC",
   "Dono_Processo": "Ricardo Nogueira — Gerente de Licitações",
   "Entregas": "Editais publicados; Contratos firmados; Atas de registro de preços",
   "Clientes_Beneficiarios": "Todas as unidades demandantes",
   "Partes_Interessadas": "Fornecedores; Assessoria Jurídica; Órgãos de controle; PNCP",
   "Sistemas": "Compras.gov.br; PNCP; Painel de Preços; SEI",
   "Normativos_Aplicaveis": "Lei nº 14.133/2021; Lei nº 13.303/2016; IN SEGES nº 65/2021; NI-027/2024 (fictícia)",
   "Imagem_Bizagi": "img/diagramas/mp-06.svg",
   "Observacoes": "Macroprocesso priorizado no ciclo 2026 de mapeamento."
  },
  {
   "Codigo": "MP-07",
   "Nome": "Gestão de Pessoas",
   "Categoria": "Suporte",
   "Ordem": 7,
   "Descricao": "Provimento, desenvolvimento, remuneração e qualidade de vida do corpo funcional.",
   "Objetivo": "Assegurar pessoas qualificadas e engajadas para a missão institucional.",
   "Unidade_Responsavel": "AG/GGP",
   "Dono_Processo": "Patrícia Ramos — Gerente de Pessoas",
   "Entregas": "Empregados admitidos e capacitados; Folha de pagamento",
   "Clientes_Beneficiarios": "Empregados; Gestores",
   "Partes_Interessadas": "Sindicatos; SEST; Ministério supervisor",
   "Sistemas": "SIGEP (fictício); SEI",
   "Normativos_Aplicaveis": "CLT; Normas internas de pessoal",
   "Imagem_Bizagi": "img/diagramas/mp-07.svg",
   "Observacoes": null
  },
  {
   "Codigo": "MP-08",
   "Nome": "Gestão de Tecnologia da Informação",
   "Categoria": "Suporte",
   "Ordem": 8,
   "Descricao": "Planejamento, desenvolvimento, sustentação e segurança dos serviços de TI.",
   "Objetivo": "Prover soluções digitais seguras que habilitem os processos de negócio.",
   "Unidade_Responsavel": "AT/GTI",
   "Dono_Processo": "Daniela Ribeiro — Gerente de TI",
   "Entregas": "Sistemas em produção; Serviços de infraestrutura; Suporte ao usuário",
   "Clientes_Beneficiarios": "Todas as unidades",
   "Partes_Interessadas": "SGD/MGI; Fornecedores de TI",
   "Sistemas": "e-Codevasf; Service Desk",
   "Normativos_Aplicaveis": "IN SGD nº 94/2022; Política de Segurança da Informação (fictícia)",
   "Imagem_Bizagi": "img/diagramas/mp-08.svg",
   "Observacoes": null
  }
 ],
 "Processos": [
  {
   "Codigo": "P-06.01",
   "Macroprocesso": "MP-06",
   "Nome": "Planejamento da Contratação",
   "Descricao": "Da identificação da necessidade (DFD) até a aprovação do ETP, TR e pesquisa de preços que instruem o certame.",
   "Objetivo": "Instruir as contratações com estudos e artefatos completos, reduzindo retrabalho e impugnações.",
   "Area_Responsavel": "AA/GLC",
   "Dono_Processo": "Ricardo Nogueira",
   "Interlocutor": "Carlos Eduardo Lima (UNP)",
   "Prioridade": "Alta",
   "Complexidade": "Alta",
   "Status_Mapeamento": "Concluído",
   "Percentual": 1,
   "Fase_Ciclo_BPM": "5. Medir o sucesso",
   "Inicio_Mapeamento": "2026-01-05",
   "Prazo_Previsto": "2026-05-29",
   "Data_Conclusao": "2026-05-18",
   "Fornecedores": "Áreas demandantes; Painel de Preços; Fornecedores (cotações)",
   "Entradas": "DFD; Plano de Contratações Anual; Requisitos da área",
   "Saidas": "ETP aprovado; TR aprovado; Pesquisa de preços validada",
   "Clientes": "AA/GLC (Seleção do Fornecedor); Assessoria Jurídica",
   "Sistemas": "SEI; Compras.gov.br; Painel de Preços",
   "Normativos_Relacionados": "Lei nº 14.133/2021; IN SEGES nº 65/2021; NI-027/2024 (fictícia)",
   "Processo_SEI": "59500.000123/2026-11",
   "Imagem_Bizagi": "img/diagramas/p-06-01.svg",
   "M1_Formulario_Enviado": "Sim",
   "M2_Formulario_Retornado": "Sim",
   "M3_Reuniao_Contextualizacao": "Sim",
   "M4_ASIS_Modelado": "Sim",
   "M5_ASIS_Validado": "Sim",
   "M6_Normativos_Identificados": "Sim",
   "M7_TOBE_Elaborado": "Sim",
   "M8_TOBE_Validado": "Sim",
   "M9_Publicado_Repositorio": "Sim",
   "Proxima_Acao": "Monitorar indicadores do processo e revisar POP em 12 meses.",
   "Pendencia": null,
   "Ultima_Atualizacao": "2026-07-10"
  },
  {
   "Codigo": "P-06.02",
   "Macroprocesso": "MP-06",
   "Nome": "Seleção do Fornecedor",
   "Descricao": "Da divulgação do edital à homologação do resultado, incluindo sessão pública, julgamento e recursos.",
   "Objetivo": "Selecionar a proposta mais vantajosa com celeridade e segurança jurídica.",
   "Area_Responsavel": "AA/GLC",
   "Dono_Processo": "Ricardo Nogueira",
   "Interlocutor": "Carlos Eduardo Lima (UNP)",
   "Prioridade": "Alta",
   "Complexidade": "Média",
   "Status_Mapeamento": "Em andamento",
   "Percentual": 0.6,
   "Fase_Ciclo_BPM": "2. Arquitetar mudanças",
   "Inicio_Mapeamento": "2026-06-01",
   "Prazo_Previsto": "2026-09-30",
   "Data_Conclusao": null,
   "Fornecedores": "P-06.01 (artefatos); Compras.gov.br",
   "Entradas": "Edital minutado; Parecer jurídico; ETP/TR",
   "Saidas": "Resultado homologado; Contrato/ata para assinatura",
   "Clientes": "Unidades demandantes; Fornecedores",
   "Sistemas": "Compras.gov.br; PNCP; SEI",
   "Normativos_Relacionados": "Lei nº 14.133/2021; NI-027/2024 (fictícia)",
   "Processo_SEI": "59500.000456/2026-22",
   "Imagem_Bizagi": "img/diagramas/p-06-02.svg",
   "M1_Formulario_Enviado": "Sim",
   "M2_Formulario_Retornado": "Sim",
   "M3_Reuniao_Contextualizacao": "Sim",
   "M4_ASIS_Modelado": "Sim",
   "M5_ASIS_Validado": "Não",
   "M6_Normativos_Identificados": "Não",
   "M7_TOBE_Elaborado": "Não",
   "M8_TOBE_Validado": "Não",
   "M9_Publicado_Repositorio": "Não",
   "Proxima_Acao": "Validar AS-IS com o dono do processo (reunião marcada).",
   "Pendencia": "Pendente retorno da área sobre fluxo de recursos administrativos.",
   "Ultima_Atualizacao": "2026-07-15"
  },
  {
   "Codigo": "P-06.03",
   "Macroprocesso": "MP-06",
   "Nome": "Gestão e Fiscalização Contratual",
   "Descricao": "Da assinatura do contrato ao encerramento, incluindo fiscalização, medições, pagamentos e sanções.",
   "Objetivo": "Garantir a entrega do objeto contratado no prazo, custo e qualidade pactuados.",
   "Area_Responsavel": "AA/GLC",
   "Dono_Processo": "Ricardo Nogueira",
   "Interlocutor": "Bruna Souza (UNP)",
   "Prioridade": "Alta",
   "Complexidade": "Alta",
   "Status_Mapeamento": "Em andamento",
   "Percentual": 0.35,
   "Fase_Ciclo_BPM": "2. Arquitetar mudanças",
   "Inicio_Mapeamento": "2026-06-15",
   "Prazo_Previsto": "2026-11-30",
   "Data_Conclusao": null,
   "Fornecedores": "P-06.02 (contrato); Fornecedores contratados",
   "Entradas": "Contrato assinado; Cronograma; Garantias",
   "Saidas": "Objeto recebido; Pagamentos efetuados; Termo de encerramento",
   "Clientes": "Unidades demandantes; Fornecedores",
   "Sistemas": "SEI; Compras.gov.br",
   "Normativos_Relacionados": "Lei nº 14.133/2021; Manual de Fiscalização (fictício)",
   "Processo_SEI": "59500.000789/2026-33",
   "Imagem_Bizagi": "img/diagramas/p-06-03.svg",
   "M1_Formulario_Enviado": "Sim",
   "M2_Formulario_Retornado": "Sim",
   "M3_Reuniao_Contextualizacao": "Sim",
   "M4_ASIS_Modelado": "Não",
   "M5_ASIS_Validado": "Não",
   "M6_Normativos_Identificados": "Não",
   "M7_TOBE_Elaborado": "Não",
   "M8_TOBE_Validado": "Não",
   "M9_Publicado_Repositorio": "Não",
   "Proxima_Acao": "Concluir modelagem AS-IS das medições e pagamentos.",
   "Pendencia": null,
   "Ultima_Atualizacao": "2026-07-20"
  },
  {
   "Codigo": "P-04.01",
   "Macroprocesso": "MP-04",
   "Nome": "Operação e Manutenção de Perímetros Irrigados",
   "Descricao": "Programação e distribuição de água, manutenção da infraestrutura de uso comum e relacionamento com irrigantes.",
   "Objetivo": "Assegurar a distribuição hídrica confiável e a conservação dos ativos.",
   "Area_Responsavel": "AI/GOM",
   "Dono_Processo": "Marcos Vinícius",
   "Interlocutor": "Eduardo Martins (UNP)",
   "Prioridade": "Média",
   "Complexidade": "Alta",
   "Status_Mapeamento": "Em andamento",
   "Percentual": 0.45,
   "Fase_Ciclo_BPM": "2. Arquitetar mudanças",
   "Inicio_Mapeamento": "2026-05-04",
   "Prazo_Previsto": "2026-10-30",
   "Data_Conclusao": null,
   "Fornecedores": "ANA (outorgas); Distritos de irrigação",
   "Entradas": "Outorga de uso; Demanda de irrigação; Plano de cultivo",
   "Saidas": "Água distribuída; Infraestrutura mantida; Relatórios de O&M",
   "Clientes": "Irrigantes; Distritos",
   "Sistemas": "SIG-Irrigação (fictício); SEI",
   "Normativos_Relacionados": "Lei nº 12.787/2013",
   "Processo_SEI": "59500.000901/2026-44",
   "Imagem_Bizagi": "img/diagramas/p-04-01.svg",
   "M1_Formulario_Enviado": "Sim",
   "M2_Formulario_Retornado": "Sim",
   "M3_Reuniao_Contextualizacao": "Sim",
   "M4_ASIS_Modelado": "Sim",
   "M5_ASIS_Validado": "Não",
   "M6_Normativos_Identificados": "Não",
   "M7_TOBE_Elaborado": "Não",
   "M8_TOBE_Validado": "Não",
   "M9_Publicado_Repositorio": "Não",
   "Proxima_Acao": "Agendar oficina de validação do AS-IS com o distrito.",
   "Pendencia": null,
   "Ultima_Atualizacao": "2026-07-12"
  },
  {
   "Codigo": "P-05.01",
   "Macroprocesso": "MP-05",
   "Nome": "Recuperação de Nascentes e Matas Ciliares",
   "Descricao": "Seleção de áreas, execução de cercamento e plantio, e monitoramento da regeneração.",
   "Objetivo": "Recuperar áreas degradadas prioritárias das bacias.",
   "Area_Responsavel": "AR/GRB",
   "Dono_Processo": "Luciana Prado",
   "Interlocutor": "Eduardo Martins (UNP)",
   "Prioridade": "Média",
   "Complexidade": "Média",
   "Status_Mapeamento": "Não iniciado",
   "Percentual": 0,
   "Fase_Ciclo_BPM": "1. Alinhamento à estratégia e metas",
   "Inicio_Mapeamento": null,
   "Prazo_Previsto": "2027-03-31",
   "Data_Conclusao": null,
   "Fornecedores": "Municípios; Comitês de bacia",
   "Entradas": "Diagnóstico hidroambiental; Termos de cooperação",
   "Saidas": "Nascentes recuperadas; Relatórios de monitoramento",
   "Clientes": "Comunidades; Órgãos ambientais",
   "Sistemas": "SEI; GeoPortal (fictício)",
   "Normativos_Relacionados": "Legislação ambiental aplicável",
   "Processo_SEI": null,
   "Imagem_Bizagi": "img/diagramas/p-05-01.svg",
   "M1_Formulario_Enviado": "Não",
   "M2_Formulario_Retornado": "Não",
   "M3_Reuniao_Contextualizacao": "Não",
   "M4_ASIS_Modelado": "Não",
   "M5_ASIS_Validado": "Não",
   "M6_Normativos_Identificados": "Não",
   "M7_TOBE_Elaborado": "Não",
   "M8_TOBE_Validado": "Não",
   "M9_Publicado_Repositorio": "Não",
   "Proxima_Acao": "Enviar formulário de levantamento à área (previsto ago/2026).",
   "Pendencia": null,
   "Ultima_Atualizacao": "2026-07-01"
  },
  {
   "Codigo": "P-01.01",
   "Macroprocesso": "MP-01",
   "Nome": "Formulação e Monitoramento do Planejamento Estratégico",
   "Descricao": "Construção do plano estratégico, desdobramento em planos de ação e monitoramento periódico de resultados.",
   "Objetivo": "Manter a estratégia viva, monitorada e comunicada.",
   "Area_Responsavel": "AE/GPE",
   "Dono_Processo": "Helena Castro",
   "Interlocutor": "Gustavo Pereira (UNP)",
   "Prioridade": "Alta",
   "Complexidade": "Média",
   "Status_Mapeamento": "Concluído",
   "Percentual": 1,
   "Fase_Ciclo_BPM": "5. Medir o sucesso",
   "Inicio_Mapeamento": "2025-09-01",
   "Prazo_Previsto": "2026-02-27",
   "Data_Conclusao": "2026-02-20",
   "Fornecedores": "Diretoria; Unidades",
   "Entradas": "Diretrizes de governo; Diagnóstico institucional",
   "Saidas": "Plano Estratégico; Painel de indicadores; RAG",
   "Clientes": "Diretoria Executiva; Conselhos",
   "Sistemas": "e-Codevasf; Painéis de BI",
   "Normativos_Relacionados": "Lei nº 13.303/2016",
   "Processo_SEI": "59500.000015/2025-77",
   "Imagem_Bizagi": "img/diagramas/p-01-01.svg",
   "M1_Formulario_Enviado": "Sim",
   "M2_Formulario_Retornado": "Sim",
   "M3_Reuniao_Contextualizacao": "Sim",
   "M4_ASIS_Modelado": "Sim",
   "M5_ASIS_Validado": "Sim",
   "M6_Normativos_Identificados": "Sim",
   "M7_TOBE_Elaborado": "Sim",
   "M8_TOBE_Validado": "Sim",
   "M9_Publicado_Repositorio": "Sim",
   "Proxima_Acao": "Ciclo de monitoramento trimestral (próximo: set/2026).",
   "Pendencia": null,
   "Ultima_Atualizacao": "2026-06-30"
  },
  {
   "Codigo": "P-07.01",
   "Macroprocesso": "MP-07",
   "Nome": "Admissão e Integração de Empregados",
   "Descricao": "Da homologação do concurso à integração do novo empregado, incluindo exames, posse e ambientação.",
   "Objetivo": "Admitir e integrar novos empregados com agilidade e conformidade.",
   "Area_Responsavel": "AG/GGP",
   "Dono_Processo": "Patrícia Ramos",
   "Interlocutor": "Bruna Souza (UNP)",
   "Prioridade": "Baixa",
   "Complexidade": "Baixa",
   "Status_Mapeamento": "Não iniciado",
   "Percentual": 0,
   "Fase_Ciclo_BPM": "1. Alinhamento à estratégia e metas",
   "Inicio_Mapeamento": null,
   "Prazo_Previsto": "2027-06-30",
   "Data_Conclusao": null,
   "Fornecedores": "Banca do concurso; Candidatos",
   "Entradas": "Resultado homologado; Documentação do candidato",
   "Saidas": "Empregado admitido e integrado",
   "Clientes": "Novos empregados; Unidades de lotação",
   "Sistemas": "SIGEP (fictício); SEI",
   "Normativos_Relacionados": "CLT; Normas internas de pessoal",
   "Processo_SEI": null,
   "Imagem_Bizagi": "img/diagramas/p-07-01.svg",
   "M1_Formulario_Enviado": "Não",
   "M2_Formulario_Retornado": "Não",
   "M3_Reuniao_Contextualizacao": "Não",
   "M4_ASIS_Modelado": "Não",
   "M5_ASIS_Validado": "Não",
   "M6_Normativos_Identificados": "Não",
   "M7_TOBE_Elaborado": "Não",
   "M8_TOBE_Validado": "Não",
   "M9_Publicado_Repositorio": "Não",
   "Proxima_Acao": "Aguardando priorização no ciclo 2027.",
   "Pendencia": null,
   "Ultima_Atualizacao": "2026-06-15"
  }
 ],
 "Subprocessos": [
  {
   "Codigo": "SP-06.01.01",
   "Processo": "P-06.01",
   "Ordem": 1,
   "Nome": "Estudo Técnico Preliminar (ETP)",
   "Descricao": "Caracterização da necessidade, análise de soluções de mercado e demonstração da viabilidade da contratação.",
   "Objetivo": "Fundamentar tecnicamente a melhor solução para a necessidade.",
   "Unidade_Responsavel": "AA/GLC",
   "Dono": "Ricardo Nogueira",
   "Entregas": "ETP aprovado no SEI",
   "Sistemas": "SEI; Compras.gov.br",
   "Imagem_Bizagi": "img/diagramas/sp-06-01-01.svg"
  },
  {
   "Codigo": "SP-06.01.02",
   "Processo": "P-06.01",
   "Ordem": 2,
   "Nome": "Termo de Referência (TR)",
   "Descricao": "Definição do objeto, requisitos, modelo de execução e gestão contratual, e critérios de julgamento.",
   "Objetivo": "Especificar com precisão o objeto e as condições da contratação.",
   "Unidade_Responsavel": "AA/GLC",
   "Dono": "Ricardo Nogueira",
   "Entregas": "TR aprovado e validado juridicamente",
   "Sistemas": "SEI",
   "Imagem_Bizagi": "img/diagramas/sp-06-01-02.svg"
  },
  {
   "Codigo": "SP-06.01.03",
   "Processo": "P-06.01",
   "Ordem": 3,
   "Nome": "Pesquisa de Preços",
   "Descricao": "Levantamento de preços em fontes admitidas (Painel de Preços, PNCP, cotações) e consolidação do valor estimado.",
   "Objetivo": "Estimar o valor da contratação conforme a IN SEGES nº 65/2021.",
   "Unidade_Responsavel": "AA/GLC",
   "Dono": "Ricardo Nogueira",
   "Entregas": "Relatório de pesquisa de preços; Mapa comparativo",
   "Sistemas": "Painel de Preços; PNCP; SEI",
   "Imagem_Bizagi": "img/diagramas/sp-06-01-03.svg"
  },
  {
   "Codigo": "SP-06.02.01",
   "Processo": "P-06.02",
   "Ordem": 1,
   "Nome": "Condução da Sessão Pública",
   "Descricao": "Abertura da sessão no sistema, fase de lances, julgamento, habilitação e registro em ata.",
   "Objetivo": "Conduzir o certame com transparência e celeridade.",
   "Unidade_Responsavel": "AA/GLC",
   "Dono": "Ricardo Nogueira",
   "Entregas": "Ata da sessão; Resultado por item",
   "Sistemas": "Compras.gov.br",
   "Imagem_Bizagi": "img/diagramas/sp-06-02-01.svg"
  },
  {
   "Codigo": "SP-04.01.01",
   "Processo": "P-04.01",
   "Ordem": 1,
   "Nome": "Distribuição de Água aos Irrigantes",
   "Descricao": "Programação semanal, operação de comportas e bombas, e registro de volumes distribuídos.",
   "Objetivo": "Entregar a água programada com eficiência e equidade.",
   "Unidade_Responsavel": "AI/GOM",
   "Dono": "Marcos Vinícius",
   "Entregas": "Programação hídrica executada; Registros de volume",
   "Sistemas": "SIG-Irrigação (fictício)",
   "Imagem_Bizagi": "img/diagramas/sp-04-01-01.svg"
  }
 ],
 "Atividades": [
  {
   "Codigo": "A-06.01.01.01",
   "Subprocesso": "SP-06.01.01",
   "Ordem": 1,
   "Nome": "Formalizar a necessidade (DFD)",
   "Descricao": "Registrar o Documento de Formalização da Demanda com justificativa, quantitativos e alinhamento ao PCA.",
   "Responsavel_Ator": "Área demandante",
   "Entradas": "Necessidade identificada; Plano de Contratações Anual",
   "Saidas": "DFD assinado no SEI",
   "Sistemas": "SEI",
   "Prazo_Padrao": "5 dias úteis",
   "Base_Normativa": "NI-027/2024 (fictícia)"
  },
  {
   "Codigo": "A-06.01.01.02",
   "Subprocesso": "SP-06.01.01",
   "Ordem": 2,
   "Nome": "Levantar soluções de mercado",
   "Descricao": "Pesquisar soluções disponíveis, contratações similares e alternativas (inclusive não contratar).",
   "Responsavel_Ator": "Equipe de planejamento da contratação",
   "Entradas": "DFD; Catálogos; Contratações similares (PNCP)",
   "Saidas": "Levantamento de soluções documentado",
   "Sistemas": "PNCP; Compras.gov.br",
   "Prazo_Padrao": "10 dias úteis",
   "Base_Normativa": "Lei nº 14.133/2021, art. 18"
  },
  {
   "Codigo": "A-06.01.01.03",
   "Subprocesso": "SP-06.01.01",
   "Ordem": 3,
   "Nome": "Estimar quantidades e resultados",
   "Descricao": "Definir quantitativos com memória de cálculo e resultados pretendidos com a contratação.",
   "Responsavel_Ator": "Equipe de planejamento da contratação",
   "Entradas": "Levantamento de soluções; Séries históricas",
   "Saidas": "Memória de cálculo de quantitativos",
   "Sistemas": "SEI",
   "Prazo_Padrao": "5 dias úteis",
   "Base_Normativa": null
  },
  {
   "Codigo": "A-06.01.01.04",
   "Subprocesso": "SP-06.01.01",
   "Ordem": 4,
   "Nome": "Elaborar e aprovar o ETP",
   "Descricao": "Consolidar o ETP no sistema e submeter à aprovação da autoridade competente.",
   "Responsavel_Ator": "Equipe de planejamento; Autoridade competente",
   "Entradas": "Levantamentos e memórias anteriores",
   "Saidas": "ETP aprovado",
   "Sistemas": "SEI; Compras.gov.br",
   "Prazo_Padrao": "7 dias úteis",
   "Base_Normativa": "Lei nº 14.133/2021, art. 18"
  },
  {
   "Codigo": "A-06.01.02.01",
   "Subprocesso": "SP-06.01.02",
   "Ordem": 1,
   "Nome": "Redigir o Termo de Referência",
   "Descricao": "Elaborar o TR a partir do ETP, definindo objeto, requisitos, modelo de execução e critérios de medição.",
   "Responsavel_Ator": "Equipe de planejamento da contratação",
   "Entradas": "ETP aprovado; Modelos padronizados",
   "Saidas": "Minuta de TR",
   "Sistemas": "SEI",
   "Prazo_Padrao": "10 dias úteis",
   "Base_Normativa": "Lei nº 14.133/2021, art. 6º, XXIII"
  },
  {
   "Codigo": "A-06.01.02.02",
   "Subprocesso": "SP-06.01.02",
   "Ordem": 2,
   "Nome": "Validar o TR com a Assessoria Jurídica",
   "Descricao": "Submeter a minuta ao órgão jurídico e ajustar conforme o parecer.",
   "Responsavel_Ator": "AA/GLC; Assessoria Jurídica",
   "Entradas": "Minuta de TR",
   "Saidas": "TR validado; Parecer jurídico",
   "Sistemas": "SEI",
   "Prazo_Padrao": "15 dias úteis",
   "Base_Normativa": "Lei nº 14.133/2021, art. 53"
  },
  {
   "Codigo": "A-06.01.03.01",
   "Subprocesso": "SP-06.01.03",
   "Ordem": 1,
   "Nome": "Realizar a pesquisa de preços",
   "Descricao": "Consultar fontes admitidas, registrar parâmetros e tratar valores inexequíveis ou excessivos.",
   "Responsavel_Ator": "Equipe de planejamento da contratação",
   "Entradas": "TR validado; Fontes de preços",
   "Saidas": "Relatório de pesquisa de preços",
   "Sistemas": "Painel de Preços; PNCP",
   "Prazo_Padrao": "10 dias úteis",
   "Base_Normativa": "IN SEGES nº 65/2021"
  },
  {
   "Codigo": "A-06.01.03.02",
   "Subprocesso": "SP-06.01.03",
   "Ordem": 2,
   "Nome": "Consolidar o valor estimado",
   "Descricao": "Aplicar o método definido (média/mediana/menor preço) e justificar a estimativa final.",
   "Responsavel_Ator": "Equipe de planejamento da contratação",
   "Entradas": "Relatório de pesquisa",
   "Saidas": "Valor estimado consolidado",
   "Sistemas": "SEI",
   "Prazo_Padrao": "3 dias úteis",
   "Base_Normativa": "IN SEGES nº 65/2021, art. 6º"
  },
  {
   "Codigo": "A-06.02.01.01",
   "Subprocesso": "SP-06.02.01",
   "Ordem": 1,
   "Nome": "Publicar o edital",
   "Descricao": "Divulgar o edital no PNCP e no sistema de compras, observando prazos mínimos legais.",
   "Responsavel_Ator": "Agente de contratação",
   "Entradas": "Edital aprovado; Parecer jurídico",
   "Saidas": "Edital publicado (PNCP)",
   "Sistemas": "Compras.gov.br; PNCP",
   "Prazo_Padrao": "2 dias úteis",
   "Base_Normativa": "Lei nº 14.133/2021, art. 54"
  },
  {
   "Codigo": "A-06.02.01.02",
   "Subprocesso": "SP-06.02.01",
   "Ordem": 2,
   "Nome": "Conduzir a sessão e julgar propostas",
   "Descricao": "Operar a fase de lances, julgar propostas, habilitar o vencedor e registrar a ata.",
   "Responsavel_Ator": "Agente de contratação; Equipe de apoio",
   "Entradas": "Edital publicado; Propostas",
   "Saidas": "Ata da sessão; Resultado do julgamento",
   "Sistemas": "Compras.gov.br",
   "Prazo_Padrao": "Conforme edital",
   "Base_Normativa": "Lei nº 14.133/2021"
  },
  {
   "Codigo": "A-04.01.01.01",
   "Subprocesso": "SP-04.01.01",
   "Ordem": 1,
   "Nome": "Programar a distribuição hídrica",
   "Descricao": "Elaborar a programação semanal de distribuição conforme demanda dos lotes e disponibilidade hídrica.",
   "Responsavel_Ator": "Equipe de operação do perímetro",
   "Entradas": "Plano de cultivo; Disponibilidade hídrica",
   "Saidas": "Programação semanal aprovada",
   "Sistemas": "SIG-Irrigação (fictício)",
   "Prazo_Padrao": "Semanal",
   "Base_Normativa": null
  },
  {
   "Codigo": "A-04.01.01.02",
   "Subprocesso": "SP-04.01.01",
   "Ordem": 2,
   "Nome": "Operar e registrar a distribuição",
   "Descricao": "Operar comportas e bombas conforme programação e registrar volumes por ponto de entrega.",
   "Responsavel_Ator": "Equipe de operação do perímetro",
   "Entradas": "Programação semanal",
   "Saidas": "Volumes registrados; Ocorrências",
   "Sistemas": "SIG-Irrigação (fictício)",
   "Prazo_Padrao": "Diário",
   "Base_Normativa": null
  }
 ],
 "Documentos": [
  {
   "ID": "DOC-001",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.01",
   "Tipo_Documento": "Procedimento Operacional (POP)",
   "Titulo": "POP 06.01 — Planejamento da Contratação",
   "Versao": "2.0",
   "Data": "2026-05-18",
   "Situacao": "Vigente",
   "Link": "https://exemplo.codevasf.gov.br/repositorio/pop-06-01.pdf",
   "Observacoes": "Publicado após validação do TO-BE."
  },
  {
   "ID": "DOC-002",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.01",
   "Tipo_Documento": "Diagrama BPMN",
   "Titulo": "Diagrama AS-IS — Planejamento da Contratação (Bizagi)",
   "Versao": "1.0",
   "Data": "2026-03-02",
   "Situacao": "Vigente",
   "Link": "img/diagramas/p-06-01.svg",
   "Observacoes": "Exportado do Bizagi Modeler."
  },
  {
   "ID": "DOC-003",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.01",
   "Tipo_Documento": "Diagrama BPMN",
   "Titulo": "Diagrama TO-BE — Planejamento da Contratação (Bizagi)",
   "Versao": "1.0",
   "Data": "2026-05-04",
   "Situacao": "Vigente",
   "Link": "https://exemplo.codevasf.gov.br/repositorio/p-06-01-tobe.pdf",
   "Observacoes": null
  },
  {
   "ID": "DOC-004",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.01",
   "Tipo_Documento": "Ata de reunião",
   "Titulo": "Ata — Reunião de contextualização com a GLC",
   "Versao": "1.0",
   "Data": "2026-01-12",
   "Situacao": "Vigente",
   "Link": "https://exemplo.codevasf.gov.br/sei/ata-contextualizacao-p0601",
   "Observacoes": "SEI 59500.000123/2026-11."
  },
  {
   "ID": "DOC-005",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.01",
   "Tipo_Documento": "Relatório",
   "Titulo": "Relatório de oportunidades de melhoria (AS-IS → TO-BE)",
   "Versao": "1.0",
   "Data": "2026-04-13",
   "Situacao": "Vigente",
   "Link": "https://exemplo.codevasf.gov.br/repositorio/rel-melhorias-p0601.pdf",
   "Observacoes": null
  },
  {
   "ID": "DOC-006",
   "Vinculo_Nivel": "Subprocesso",
   "Vinculo_Codigo": "SP-06.01.01",
   "Tipo_Documento": "Formulário/Modelo",
   "Titulo": "Modelo de DFD — Documento de Formalização da Demanda",
   "Versao": "3.1",
   "Data": "2026-02-10",
   "Situacao": "Vigente",
   "Link": "https://exemplo.codevasf.gov.br/modelos/dfd.docx",
   "Observacoes": null
  },
  {
   "ID": "DOC-007",
   "Vinculo_Nivel": "Subprocesso",
   "Vinculo_Codigo": "SP-06.01.03",
   "Tipo_Documento": "Procedimento Operacional (POP)",
   "Titulo": "Roteiro de pesquisa de preços (IN SEGES nº 65/2021)",
   "Versao": "1.2",
   "Data": "2026-04-27",
   "Situacao": "Vigente",
   "Link": "https://exemplo.codevasf.gov.br/repositorio/roteiro-precos.pdf",
   "Observacoes": null
  },
  {
   "ID": "DOC-008",
   "Vinculo_Nivel": "Macroprocesso",
   "Vinculo_Codigo": "MP-06",
   "Tipo_Documento": "Norma interna",
   "Titulo": "NI-027/2024 — Norma de Licitações e Contratos (fictícia)",
   "Versao": "4.0",
   "Data": "2024-11-20",
   "Situacao": "Vigente",
   "Link": "https://exemplo.codevasf.gov.br/normativos/ni-027",
   "Observacoes": null
  },
  {
   "ID": "DOC-009",
   "Vinculo_Nivel": "Macroprocesso",
   "Vinculo_Codigo": "MP-06",
   "Tipo_Documento": "Manual",
   "Titulo": "Manual de Gestão e Fiscalização de Contratos (fictício)",
   "Versao": "2.3",
   "Data": "2025-08-14",
   "Situacao": "Em revisão",
   "Link": "https://exemplo.codevasf.gov.br/normativos/manual-fiscalizacao",
   "Observacoes": null
  },
  {
   "ID": "DOC-010",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.02",
   "Tipo_Documento": "Ata de reunião",
   "Titulo": "Ata — Contextualização do processo Seleção do Fornecedor",
   "Versao": "1.0",
   "Data": "2026-06-02",
   "Situacao": "Vigente",
   "Link": "https://exemplo.codevasf.gov.br/sei/ata-contextualizacao-p0602",
   "Observacoes": null
  },
  {
   "ID": "DOC-011",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-04.01",
   "Tipo_Documento": "Diagrama BPMN",
   "Titulo": "Diagrama AS-IS parcial — O&M de Perímetros (Bizagi)",
   "Versao": "0.3",
   "Data": "2026-07-08",
   "Situacao": "Em elaboração",
   "Link": "img/diagramas/p-04-01.svg",
   "Observacoes": "Modelagem em curso."
  },
  {
   "ID": "DOC-012",
   "Vinculo_Nivel": "Atividade",
   "Vinculo_Codigo": "A-06.01.01.01",
   "Tipo_Documento": "Formulário/Modelo",
   "Titulo": "Passo a passo do DFD no SEI",
   "Versao": "1.0",
   "Data": "2026-02-12",
   "Situacao": "Vigente",
   "Link": "https://exemplo.codevasf.gov.br/modelos/dfd-sei-passoapasso.pdf",
   "Observacoes": null
  },
  {
   "ID": "DOC-013",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-01.01",
   "Tipo_Documento": "Relatório",
   "Titulo": "Caderno de Indicadores Estratégicos 2026",
   "Versao": "1.0",
   "Data": "2026-03-31",
   "Situacao": "Vigente",
   "Link": "https://exemplo.codevasf.gov.br/estrategia/caderno-2026.pdf",
   "Observacoes": null
  },
  {
   "ID": "DOC-014",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.01",
   "Tipo_Documento": "Plano",
   "Titulo": "Plano de implantação do TO-BE (PMBOK — plano do projeto)",
   "Versao": "1.0",
   "Data": "2026-05-06",
   "Situacao": "Vigente",
   "Link": "https://exemplo.codevasf.gov.br/repositorio/plano-tobe-p0601.pdf",
   "Observacoes": null
  }
 ],
 "Riscos": [
  {
   "ID": "R-001",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.01",
   "Descricao_Risco": "Estimativas de preço defasadas gerando sobrepreço ou licitação deserta.",
   "Categoria": "Operacional",
   "Probabilidade_1a5": 4,
   "Impacto_1a5": 4,
   "Nivel_PxI": 16,
   "Classificacao": "Alto",
   "Resposta": "Mitigar",
   "Controles_Tratamento": "Roteiro de pesquisa com múltiplas fontes (Painel de Preços, PNCP) e revisão pela UNP.",
   "Responsavel": "Ricardo Nogueira",
   "Status": "Em tratamento"
  },
  {
   "ID": "R-002",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.01",
   "Descricao_Risco": "TR genérico ou restritivo provocando impugnações e atrasos no certame.",
   "Categoria": "Legal/Conformidade",
   "Probabilidade_1a5": 3,
   "Impacto_1a5": 4,
   "Nivel_PxI": 12,
   "Classificacao": "Alto",
   "Resposta": "Mitigar",
   "Controles_Tratamento": "Checklist de revisão e validação obrigatória pela Assessoria Jurídica.",
   "Responsavel": "Ricardo Nogueira",
   "Status": "Em tratamento"
  },
  {
   "ID": "R-003",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.03",
   "Descricao_Risco": "Fiscalização intempestiva de contratos, com medições e pagamentos atrasados.",
   "Categoria": "Operacional",
   "Probabilidade_1a5": 3,
   "Impacto_1a5": 5,
   "Nivel_PxI": 15,
   "Classificacao": "Alto",
   "Resposta": "Mitigar",
   "Controles_Tratamento": "Designação formal de fiscais, agenda de medições e alertas no SEI.",
   "Responsavel": "Ricardo Nogueira",
   "Status": "Aberto"
  },
  {
   "ID": "R-004",
   "Vinculo_Nivel": "Subprocesso",
   "Vinculo_Codigo": "SP-06.01.01",
   "Descricao_Risco": "Conhecimento concentrado em um único empregado (pessoa-chave) na elaboração de ETP.",
   "Categoria": "Pessoas",
   "Probabilidade_1a5": 4,
   "Impacto_1a5": 3,
   "Nivel_PxI": 12,
   "Classificacao": "Alto",
   "Resposta": "Mitigar",
   "Controles_Tratamento": "Publicar POP, treinar substitutos e revezar a equipe de planejamento.",
   "Responsavel": "Patrícia Ramos",
   "Status": "Em tratamento"
  },
  {
   "ID": "R-005",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-04.01",
   "Descricao_Risco": "Indisponibilidade hídrica comprometendo a programação de distribuição.",
   "Categoria": "Operacional",
   "Probabilidade_1a5": 2,
   "Impacto_1a5": 5,
   "Nivel_PxI": 10,
   "Classificacao": "Moderado",
   "Resposta": "Mitigar",
   "Controles_Tratamento": "Plano de contingência hídrica e priorização de culturas conforme regras do perímetro.",
   "Responsavel": "Marcos Vinícius",
   "Status": "Aberto"
  },
  {
   "ID": "R-006",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.02",
   "Descricao_Risco": "Instabilidade do Compras.gov.br durante a sessão pública.",
   "Categoria": "Tecnologia da Informação",
   "Probabilidade_1a5": 2,
   "Impacto_1a5": 4,
   "Nivel_PxI": 8,
   "Classificacao": "Moderado",
   "Resposta": "Mitigar",
   "Controles_Tratamento": "Protocolo de suspensão formal da sessão e comunicação imediata aos licitantes.",
   "Responsavel": "Daniela Ribeiro",
   "Status": "Aberto"
  },
  {
   "ID": "R-007",
   "Vinculo_Nivel": "Macroprocesso",
   "Vinculo_Codigo": "MP-06",
   "Descricao_Risco": "Alterações normativas frequentes exigindo atualização contínua de procedimentos.",
   "Categoria": "Legal/Conformidade",
   "Probabilidade_1a5": 4,
   "Impacto_1a5": 2,
   "Nivel_PxI": 8,
   "Classificacao": "Moderado",
   "Resposta": "Mitigar",
   "Controles_Tratamento": "Monitoramento normativo mensal (resenha) e revisão programada dos POPs.",
   "Responsavel": "Bruna Souza",
   "Status": "Em tratamento"
  },
  {
   "ID": "R-008",
   "Vinculo_Nivel": "Atividade",
   "Vinculo_Codigo": "A-06.01.03.01",
   "Descricao_Risco": "Uso de fontes de preço não admitidas pela IN SEGES nº 65/2021.",
   "Categoria": "Legal/Conformidade",
   "Probabilidade_1a5": 2,
   "Impacto_1a5": 3,
   "Nivel_PxI": 6,
   "Classificacao": "Moderado",
   "Resposta": "Mitigar",
   "Controles_Tratamento": "Validação da pesquisa pela UNP antes da aprovação do valor estimado.",
   "Responsavel": "Carlos Eduardo Lima",
   "Status": "Encerrado"
  },
  {
   "ID": "R-009",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.01",
   "Descricao_Risco": "Baixo engajamento das áreas demandantes no preenchimento do DFD.",
   "Categoria": "Pessoas",
   "Probabilidade_1a5": 3,
   "Impacto_1a5": 3,
   "Nivel_PxI": 9,
   "Classificacao": "Moderado",
   "Resposta": "Mitigar",
   "Controles_Tratamento": "Oficinas de capacitação e modelo simplificado de DFD no SEI.",
   "Responsavel": "Bruna Souza",
   "Status": "Encerrado"
  }
 ],
 "Indicadores": [
  {
   "ID": "IND-001",
   "Vinculo_Nivel": "Macroprocesso",
   "Vinculo_Codigo": "MP-06",
   "Nome": "Tempo médio do ciclo de contratação",
   "Descricao_Formula": "Média de dias entre o DFD e a homologação do certame.",
   "Unidade": "dias",
   "Polaridade": "Menor melhor",
   "Meta": 120,
   "Resultado_Atual": 148,
   "Situacao": "Acima da meta",
   "Periodicidade": "Trimestral",
   "Fonte": "Compras.gov.br",
   "Ultima_Medicao": "2026-06-30"
  },
  {
   "ID": "IND-002",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.01",
   "Nome": "Prazo médio de elaboração do ETP",
   "Descricao_Formula": "Média de dias úteis entre o DFD e a aprovação do ETP.",
   "Unidade": "dias",
   "Polaridade": "Menor melhor",
   "Meta": 30,
   "Resultado_Atual": 26,
   "Situacao": "Meta atingida",
   "Periodicidade": "Mensal",
   "Fonte": "SEI",
   "Ultima_Medicao": "2026-06-30"
  },
  {
   "ID": "IND-003",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.02",
   "Nome": "Impugnações por edital",
   "Descricao_Formula": "Nº médio de impugnações recebidas por edital publicado.",
   "Unidade": "nº",
   "Polaridade": "Menor melhor",
   "Meta": 1,
   "Resultado_Atual": 0.8,
   "Situacao": "Meta atingida",
   "Periodicidade": "Trimestral",
   "Fonte": "Compras.gov.br",
   "Ultima_Medicao": "2026-06-30"
  },
  {
   "ID": "IND-004",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-06.03",
   "Nome": "Contratos com fiscal designado",
   "Descricao_Formula": "% de contratos vigentes com fiscal formalmente designado.",
   "Unidade": "%",
   "Polaridade": "Maior melhor",
   "Meta": 100,
   "Resultado_Atual": 92,
   "Situacao": "Abaixo da meta",
   "Periodicidade": "Mensal",
   "Fonte": "SEI",
   "Ultima_Medicao": "2026-06-30"
  },
  {
   "ID": "IND-005",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-04.01",
   "Nome": "Eficiência no uso da água",
   "Descricao_Formula": "Relação % entre volume faturado e volume captado no perímetro.",
   "Unidade": "%",
   "Polaridade": "Maior melhor",
   "Meta": 75,
   "Resultado_Atual": 71,
   "Situacao": "Abaixo da meta",
   "Periodicidade": "Mensal",
   "Fonte": "SIG-Irrigação (fictício)",
   "Ultima_Medicao": "2026-06-30"
  },
  {
   "ID": "IND-006",
   "Vinculo_Nivel": "Macroprocesso",
   "Vinculo_Codigo": "MP-06",
   "Nome": "Processos com mapeamento concluído",
   "Descricao_Formula": "% de processos do macroprocesso com marco M9 concluído.",
   "Unidade": "%",
   "Polaridade": "Maior melhor",
   "Meta": 100,
   "Resultado_Atual": 33,
   "Situacao": "Abaixo da meta",
   "Periodicidade": "Trimestral",
   "Fonte": "Painel de Processos",
   "Ultima_Medicao": "2026-06-30"
  },
  {
   "ID": "IND-007",
   "Vinculo_Nivel": "Processo",
   "Vinculo_Codigo": "P-01.01",
   "Nome": "Ações estratégicas monitoradas no prazo",
   "Descricao_Formula": "% de ações do plano com status atualizado no ciclo.",
   "Unidade": "%",
   "Polaridade": "Maior melhor",
   "Meta": 95,
   "Resultado_Atual": 97,
   "Situacao": "Meta atingida",
   "Periodicidade": "Trimestral",
   "Fonte": "Painéis de BI",
   "Ultima_Medicao": "2026-06-30"
  },
  {
   "ID": "IND-008",
   "Vinculo_Nivel": "Subprocesso",
   "Vinculo_Codigo": "SP-06.01.03",
   "Nome": "Pesquisas de preço com 3+ fontes",
   "Descricao_Formula": "% de pesquisas de preços com três ou mais fontes admitidas.",
   "Unidade": "%",
   "Polaridade": "Maior melhor",
   "Meta": 100,
   "Resultado_Atual": 88,
   "Situacao": "Abaixo da meta",
   "Periodicidade": "Mensal",
   "Fonte": "SEI",
   "Ultima_Medicao": "2026-06-30"
  },
  {
   "ID": "IND-009",
   "Vinculo_Nivel": "Macroprocesso",
   "Vinculo_Codigo": "MP-05",
   "Nome": "Nascentes recuperadas no ano",
   "Descricao_Formula": "Nº de nascentes com recuperação concluída no exercício.",
   "Unidade": "nº",
   "Polaridade": "Maior melhor",
   "Meta": 120,
   "Resultado_Atual": null,
   "Situacao": "Sem medição",
   "Periodicidade": "Anual",
   "Fonte": "GeoPortal (fictício)",
   "Ultima_Medicao": null
  }
 ],
 "Diario_Mapeamento": [
  {
   "ID": "REG-001",
   "Processo": "P-06.01",
   "Data": "2026-01-05",
   "Tipo": "Marco",
   "Titulo": "Abertura do projeto de mapeamento",
   "Descricao": "Aprovação do termo de abertura do projeto de mapeamento do processo, com escopo, equipe e cronograma.",
   "Autor": "Bruna Souza",
   "Participantes": "Bruna Souza; Ricardo Nogueira; Carlos Eduardo Lima",
   "Entradas_Insumos": "Plano de ação 2026; Priorização da carteira de processos",
   "Saidas_Entregaveis": "Termo de abertura aprovado (TAP)",
   "Evidencias": "Termo de abertura|https://exemplo.codevasf.gov.br/sei/tap-p0601",
   "Memoria": "Escopo limitado ao planejamento da contratação; seleção e gestão contratual tratadas em projetos próprios."
  },
  {
   "ID": "REG-002",
   "Processo": "P-06.01",
   "Data": "2026-01-12",
   "Tipo": "Reunião",
   "Titulo": "Reunião de contextualização com a GLC",
   "Descricao": "Apresentação da metodologia, entendimento do contexto do processo e definição dos interlocutores.",
   "Autor": "Carlos Eduardo Lima",
   "Participantes": "Equipe GLC; Ricardo Nogueira; Bruna Souza; Carlos Eduardo Lima",
   "Entradas_Insumos": "Formulário de levantamento preenchido",
   "Saidas_Entregaveis": "Ata da reunião; Lista preliminar de atividades",
   "Evidencias": "Ata|https://exemplo.codevasf.gov.br/sei/ata-contextualizacao-p0601",
   "Memoria": "A área destacou gargalo na pesquisa de preços e retrabalho na aprovação do ETP."
  },
  {
   "ID": "REG-003",
   "Processo": "P-06.01",
   "Data": "2026-01-26",
   "Tipo": "Entrevista",
   "Titulo": "Entrevista com a equipe de ETP",
   "Descricao": "Detalhamento das atividades de elaboração do ETP, entradas, saídas e sistemas utilizados.",
   "Autor": "Carlos Eduardo Lima",
   "Participantes": "Equipe de planejamento da contratação",
   "Entradas_Insumos": "Roteiro de entrevista; Amostras de ETP",
   "Saidas_Entregaveis": "Registro de entrevista; Insumos para o AS-IS",
   "Evidencias": "Registro de entrevista|https://exemplo.codevasf.gov.br/sei/entrevista-etp",
   "Memoria": null
  },
  {
   "ID": "REG-004",
   "Processo": "P-06.01",
   "Data": "2026-02-09",
   "Tipo": "Oficina",
   "Titulo": "Oficina de modelagem AS-IS",
   "Descricao": "Modelagem colaborativa do fluxo atual em BPMN no Bizagi Modeler, com validação visual dos participantes.",
   "Autor": "Daniela Ribeiro",
   "Participantes": "Equipe GLC; UNP",
   "Entradas_Insumos": "Insumos das entrevistas; Notação BPMN 2.0",
   "Saidas_Entregaveis": "Diagrama BPMN AS-IS v0.1",
   "Evidencias": "Diagrama AS-IS v0.1|img/diagramas/p-06-01.svg",
   "Memoria": "Identificados 3 retrabalhos e 2 handoffs desnecessários (princípios de desenho do CBOK)."
  },
  {
   "ID": "REG-005",
   "Processo": "P-06.01",
   "Data": "2026-03-02",
   "Tipo": "Validação",
   "Titulo": "Validação do AS-IS com o dono do processo",
   "Descricao": "Revisão e aprovação formal do diagrama AS-IS pelo dono do processo.",
   "Autor": "Carlos Eduardo Lima",
   "Participantes": "Ricardo Nogueira; Equipe GLC; UNP",
   "Entradas_Insumos": "Diagrama AS-IS v0.1",
   "Saidas_Entregaveis": "Diagrama AS-IS v1.0 validado",
   "Evidencias": "Diagrama AS-IS v1.0|img/diagramas/p-06-01.svg;Ata de validação|https://exemplo.codevasf.gov.br/sei/ata-validacao-asis",
   "Memoria": null
  },
  {
   "ID": "REG-006",
   "Processo": "P-06.01",
   "Data": "2026-03-16",
   "Tipo": "Decisão",
   "Titulo": "Definição do escopo do TO-BE",
   "Descricao": "Decisão de incorporar o roteiro de pesquisa de preços e o modelo simplificado de DFD no redesenho.",
   "Autor": "Bruna Souza",
   "Participantes": "Ricardo Nogueira; Bruna Souza",
   "Entradas_Insumos": "Relatório preliminar de melhorias",
   "Saidas_Entregaveis": "Escopo do TO-BE registrado",
   "Evidencias": "Registro de decisão|https://exemplo.codevasf.gov.br/sei/decisao-tobe",
   "Memoria": "Priorizado o redesenho 'de fora para dentro', a partir da área demandante (cliente interno)."
  },
  {
   "ID": "REG-007",
   "Processo": "P-06.01",
   "Data": "2026-04-13",
   "Tipo": "Entrega",
   "Titulo": "TO-BE elaborado",
   "Descricao": "Entrega do diagrama TO-BE e do relatório de oportunidades de melhoria.",
   "Autor": "Daniela Ribeiro",
   "Participantes": "UNP; Equipe GLC",
   "Entradas_Insumos": "AS-IS validado; Boas práticas (CBOK cap. 6)",
   "Saidas_Entregaveis": "Diagrama TO-BE v0.1; Relatório de melhorias",
   "Evidencias": "Relatório de melhorias|https://exemplo.codevasf.gov.br/repositorio/rel-melhorias-p0601.pdf",
   "Memoria": null
  },
  {
   "ID": "REG-008",
   "Processo": "P-06.01",
   "Data": "2026-05-04",
   "Tipo": "Validação",
   "Titulo": "Validação do TO-BE",
   "Descricao": "Aprovação do redesenho pelo dono do processo e pela gerência da área.",
   "Autor": "Carlos Eduardo Lima",
   "Participantes": "Ricardo Nogueira; Gerência AA",
   "Entradas_Insumos": "Diagrama TO-BE v0.1",
   "Saidas_Entregaveis": "Diagrama TO-BE v1.0 validado",
   "Evidencias": "Ata de validação TO-BE|https://exemplo.codevasf.gov.br/sei/ata-validacao-tobe",
   "Memoria": null
  },
  {
   "ID": "REG-009",
   "Processo": "P-06.01",
   "Data": "2026-05-18",
   "Tipo": "Marco",
   "Titulo": "Publicação no repositório de processos",
   "Descricao": "Publicação do POP 06.01 e dos diagramas no repositório corporativo; encerramento do projeto.",
   "Autor": "Bruna Souza",
   "Participantes": "UNP",
   "Entradas_Insumos": "TO-BE validado; POP revisado",
   "Saidas_Entregaveis": "POP 06.01 v2.0 publicado; Página do processo no painel",
   "Evidencias": "POP 06.01|https://exemplo.codevasf.gov.br/repositorio/pop-06-01.pdf",
   "Memoria": "Lições aprendidas registradas para o próximo ciclo (PMBOK — encerramento)."
  },
  {
   "ID": "REG-010",
   "Processo": "P-06.01",
   "Data": "2026-06-15",
   "Tipo": "Reunião",
   "Titulo": "Monitoramento de indicadores (fase 5)",
   "Descricao": "Primeira reunião do ciclo de medição do processo redesenhado (CBOK — medir o sucesso).",
   "Autor": "Gustavo Pereira",
   "Participantes": "UNP; GLC",
   "Entradas_Insumos": "Dados de mai/2026 (SEI e Compras.gov.br)",
   "Saidas_Entregaveis": "Ata; Ajuste da meta do IND-002",
   "Evidencias": "Ata de monitoramento|https://exemplo.codevasf.gov.br/sei/ata-monitoramento-jun26",
   "Memoria": null
  },
  {
   "ID": "REG-011",
   "Processo": "P-06.02",
   "Data": "2026-06-02",
   "Tipo": "Reunião",
   "Titulo": "Contextualização — Seleção do Fornecedor",
   "Descricao": "Início do mapeamento do processo de seleção, com apresentação do método e coleta do formulário.",
   "Autor": "Carlos Eduardo Lima",
   "Participantes": "Equipe GLC; UNP",
   "Entradas_Insumos": "Formulário de levantamento preenchido",
   "Saidas_Entregaveis": "Ata; Cronograma do projeto",
   "Evidencias": "Ata|https://exemplo.codevasf.gov.br/sei/ata-contextualizacao-p0602",
   "Memoria": null
  },
  {
   "ID": "REG-012",
   "Processo": "P-06.02",
   "Data": "2026-06-30",
   "Tipo": "Oficina",
   "Titulo": "Oficina de modelagem AS-IS (sessão 1)",
   "Descricao": "Modelagem do fluxo da sessão pública e do julgamento de propostas.",
   "Autor": "Daniela Ribeiro",
   "Participantes": "Agentes de contratação; UNP",
   "Entradas_Insumos": "Insumos da contextualização",
   "Saidas_Entregaveis": "Diagrama AS-IS parcial v0.2",
   "Evidencias": "Diagrama parcial|img/diagramas/p-06-02.svg",
   "Memoria": "Fluxo de recursos administrativos ainda pendente de detalhamento com a área."
  },
  {
   "ID": "REG-013",
   "Processo": "P-04.01",
   "Data": "2026-07-10",
   "Tipo": "Entrevista",
   "Titulo": "Entrevista — operação do perímetro",
   "Descricao": "Levantamento das rotinas de programação e distribuição hídrica com a equipe de campo.",
   "Autor": "Eduardo Martins",
   "Participantes": "Equipe de operação; UNP",
   "Entradas_Insumos": "Roteiro de entrevista",
   "Saidas_Entregaveis": "Registro de entrevista; Insumos para o AS-IS",
   "Evidencias": "Registro|https://exemplo.codevasf.gov.br/sei/entrevista-p0401",
   "Memoria": null
  }
 ]
};
